export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const SET_APPOINTMENTS = "SET_APPOINTMENTS";
export const CREATE_NEW_APPOINTMENT = "CREATE_NEW_APPOINTMENT";
export const CREATE_NEW_QR_CODE = "CREATE_NEW_QR_CODE";
export const LATEST_APPOINTMENT_STATUS = "LATEST_APPOINTMENT_STATUS";